name: Auto Publish Finance/Business Short (Hybrid)

on:
  schedule:
    - cron: "0 9 * * *"  # Daily at 09:00 UTC
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y espeak-ng ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content (video, thumbnail, metadata)
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          AFFILIATE_LINK: ${{ secrets.AFFILIATE_LINK }}
          FORCE_MODE: ${{ vars.FORCE_MODE }}
        run: |
          python scripts/generate_content.py

      - name: Upload to YouTube
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: |
          python scripts/upload_to_youtube.py out/video.mp4 out/thumbnail.png out/metadata.json
